/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 * Run `npx convex dev` to regenerate it.
 *
 * This is a placeholder file that allows the build to succeed.
 * The real file will be generated by `npx convex dev`.
 */

// Placeholder exports - these will be replaced by real generated code
export const api = {
  users: {} as any,
  teams: {} as any,
  members: {} as any,
  invites: {} as any,
  parts: {} as any,
  vendors: {} as any,
  orders: {} as any,
  bom: {} as any,
  seasons: {} as any,
};

export const internal = {} as any;
