/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 * Run `npx convex dev` to regenerate it.
 *
 * This is a placeholder file that allows the build to succeed.
 * The real file will be generated by `npx convex dev`.
 */

// Placeholder Id type
export type Id<T extends string> = string & { __tableName: T };

// Placeholder DataModel type
export type DataModel = Record<string, any>;
