/* eslint-disable */
/**
 * Generated server utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 * Run `npx convex dev` to regenerate it.
 *
 * This is a placeholder file that allows the build to succeed.
 * The real file will be generated by `npx convex dev`.
 */

import {
  mutation as baseMutation,
  query as baseQuery,
  internalMutation as baseInternalMutation,
  internalQuery as baseInternalQuery,
  action as baseAction,
  internalAction as baseInternalAction,
} from "convex/server";

// Re-export with typed data model
export const mutation = baseMutation as any;
export const query = baseQuery as any;
export const internalMutation = baseInternalMutation as any;
export const internalQuery = baseInternalQuery as any;
export const action = baseAction as any;
export const internalAction = baseInternalAction as any;

// Placeholder QueryCtx and MutationCtx types
export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;
