/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VendorsRouteImport } from "./routes/vendors";
import { Route as OnboardingRouteImport } from "./routes/onboarding";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TeamsIndexRouteImport } from "./routes/teams/index";
import { Route as TeamsNewRouteImport } from "./routes/teams/new";
import { Route as TeamsJoinRouteImport } from "./routes/teams/join";
import { Route as TeamProgramNumberRouteImport } from "./routes/team/$program/$number";
import { Route as TeamProgramNumberIndexRouteImport } from "./routes/team/$program/$number/index";
import { Route as TeamProgramNumberSettingsIndexRouteImport } from "./routes/team/$program/$number/settings/index";
import { Route as TeamProgramNumberRobotsIndexRouteImport } from "./routes/team/$program/$number/robots/index";
import { Route as TeamProgramNumberPartsIndexRouteImport } from "./routes/team/$program/$number/parts/index";
import { Route as TeamProgramNumberOrdersIndexRouteImport } from "./routes/team/$program/$number/orders/index";
import { Route as TeamProgramNumberMembersIndexRouteImport } from "./routes/team/$program/$number/members/index";
import { Route as TeamProgramNumberPartsNewIndexRouteImport } from "./routes/team/$program/$number/parts/new/index";
import { Route as TeamProgramNumberPartsPartIdIndexRouteImport } from "./routes/team/$program/$number/parts/$partId/index";
import { Route as TeamProgramNumberOrdersOrderIdIndexRouteImport } from "./routes/team/$program/$number/orders/$orderId/index";
import { Route as TeamProgramNumberPartsPartIdEditIndexRouteImport } from "./routes/team/$program/$number/parts/$partId/edit/index";

const VendorsRoute = VendorsRouteImport.update({
  id: "/vendors",
  path: "/vendors",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: "/teams/",
  path: "/teams/",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: "/teams/new",
  path: "/teams/new",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsJoinRoute = TeamsJoinRouteImport.update({
  id: "/teams/join",
  path: "/teams/join",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamProgramNumberRoute = TeamProgramNumberRouteImport.update({
  id: "/team/$program/$number",
  path: "/team/$program/$number",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamProgramNumberIndexRoute = TeamProgramNumberIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TeamProgramNumberRoute,
} as any);
const TeamProgramNumberSettingsIndexRoute =
  TeamProgramNumberSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberRobotsIndexRoute =
  TeamProgramNumberRobotsIndexRouteImport.update({
    id: "/robots/",
    path: "/robots/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsIndexRoute =
  TeamProgramNumberPartsIndexRouteImport.update({
    id: "/parts/",
    path: "/parts/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOrdersIndexRoute =
  TeamProgramNumberOrdersIndexRouteImport.update({
    id: "/orders/",
    path: "/orders/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberMembersIndexRoute =
  TeamProgramNumberMembersIndexRouteImport.update({
    id: "/members/",
    path: "/members/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsNewIndexRoute =
  TeamProgramNumberPartsNewIndexRouteImport.update({
    id: "/parts/new/",
    path: "/parts/new/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsPartIdIndexRoute =
  TeamProgramNumberPartsPartIdIndexRouteImport.update({
    id: "/parts/$partId/",
    path: "/parts/$partId/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOrdersOrderIdIndexRoute =
  TeamProgramNumberOrdersOrderIdIndexRouteImport.update({
    id: "/orders/$orderId/",
    path: "/orders/$orderId/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsPartIdEditIndexRoute =
  TeamProgramNumberPartsPartIdEditIndexRouteImport.update({
    id: "/parts/$partId/edit/",
    path: "/parts/$partId/edit/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/join": typeof TeamsJoinRoute;
  "/teams/new": typeof TeamsNewRoute;
  "/teams": typeof TeamsIndexRoute;
  "/team/$program/$number": typeof TeamProgramNumberRouteWithChildren;
  "/team/$program/$number/": typeof TeamProgramNumberIndexRoute;
  "/team/$program/$number/members": typeof TeamProgramNumberMembersIndexRoute;
  "/team/$program/$number/orders": typeof TeamProgramNumberOrdersIndexRoute;
  "/team/$program/$number/parts": typeof TeamProgramNumberPartsIndexRoute;
  "/team/$program/$number/robots": typeof TeamProgramNumberRobotsIndexRoute;
  "/team/$program/$number/settings": typeof TeamProgramNumberSettingsIndexRoute;
  "/team/$program/$number/orders/$orderId": typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  "/team/$program/$number/parts/$partId": typeof TeamProgramNumberPartsPartIdIndexRoute;
  "/team/$program/$number/parts/new": typeof TeamProgramNumberPartsNewIndexRoute;
  "/team/$program/$number/parts/$partId/edit": typeof TeamProgramNumberPartsPartIdEditIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/join": typeof TeamsJoinRoute;
  "/teams/new": typeof TeamsNewRoute;
  "/teams": typeof TeamsIndexRoute;
  "/team/$program/$number": typeof TeamProgramNumberIndexRoute;
  "/team/$program/$number/members": typeof TeamProgramNumberMembersIndexRoute;
  "/team/$program/$number/orders": typeof TeamProgramNumberOrdersIndexRoute;
  "/team/$program/$number/parts": typeof TeamProgramNumberPartsIndexRoute;
  "/team/$program/$number/robots": typeof TeamProgramNumberRobotsIndexRoute;
  "/team/$program/$number/settings": typeof TeamProgramNumberSettingsIndexRoute;
  "/team/$program/$number/orders/$orderId": typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  "/team/$program/$number/parts/$partId": typeof TeamProgramNumberPartsPartIdIndexRoute;
  "/team/$program/$number/parts/new": typeof TeamProgramNumberPartsNewIndexRoute;
  "/team/$program/$number/parts/$partId/edit": typeof TeamProgramNumberPartsPartIdEditIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/join": typeof TeamsJoinRoute;
  "/teams/new": typeof TeamsNewRoute;
  "/teams/": typeof TeamsIndexRoute;
  "/team/$program/$number": typeof TeamProgramNumberRouteWithChildren;
  "/team/$program/$number/": typeof TeamProgramNumberIndexRoute;
  "/team/$program/$number/members/": typeof TeamProgramNumberMembersIndexRoute;
  "/team/$program/$number/orders/": typeof TeamProgramNumberOrdersIndexRoute;
  "/team/$program/$number/parts/": typeof TeamProgramNumberPartsIndexRoute;
  "/team/$program/$number/robots/": typeof TeamProgramNumberRobotsIndexRoute;
  "/team/$program/$number/settings/": typeof TeamProgramNumberSettingsIndexRoute;
  "/team/$program/$number/orders/$orderId/": typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  "/team/$program/$number/parts/$partId/": typeof TeamProgramNumberPartsPartIdIndexRoute;
  "/team/$program/$number/parts/new/": typeof TeamProgramNumberPartsNewIndexRoute;
  "/team/$program/$number/parts/$partId/edit/": typeof TeamProgramNumberPartsPartIdEditIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/onboarding"
    | "/vendors"
    | "/teams/join"
    | "/teams/new"
    | "/teams"
    | "/team/$program/$number"
    | "/team/$program/$number/"
    | "/team/$program/$number/members"
    | "/team/$program/$number/orders"
    | "/team/$program/$number/parts"
    | "/team/$program/$number/robots"
    | "/team/$program/$number/settings"
    | "/team/$program/$number/orders/$orderId"
    | "/team/$program/$number/parts/$partId"
    | "/team/$program/$number/parts/new"
    | "/team/$program/$number/parts/$partId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/onboarding"
    | "/vendors"
    | "/teams/join"
    | "/teams/new"
    | "/teams"
    | "/team/$program/$number"
    | "/team/$program/$number/members"
    | "/team/$program/$number/orders"
    | "/team/$program/$number/parts"
    | "/team/$program/$number/robots"
    | "/team/$program/$number/settings"
    | "/team/$program/$number/orders/$orderId"
    | "/team/$program/$number/parts/$partId"
    | "/team/$program/$number/parts/new"
    | "/team/$program/$number/parts/$partId/edit";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/onboarding"
    | "/vendors"
    | "/teams/join"
    | "/teams/new"
    | "/teams/"
    | "/team/$program/$number"
    | "/team/$program/$number/"
    | "/team/$program/$number/members/"
    | "/team/$program/$number/orders/"
    | "/team/$program/$number/parts/"
    | "/team/$program/$number/robots/"
    | "/team/$program/$number/settings/"
    | "/team/$program/$number/orders/$orderId/"
    | "/team/$program/$number/parts/$partId/"
    | "/team/$program/$number/parts/new/"
    | "/team/$program/$number/parts/$partId/edit/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  VendorsRoute: typeof VendorsRoute;
  TeamsJoinRoute: typeof TeamsJoinRoute;
  TeamsNewRoute: typeof TeamsNewRoute;
  TeamsIndexRoute: typeof TeamsIndexRoute;
  TeamProgramNumberRoute: typeof TeamProgramNumberRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vendors": {
      id: "/vendors";
      path: "/vendors";
      fullPath: "/vendors";
      preLoaderRoute: typeof VendorsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/": {
      id: "/teams/";
      path: "/teams";
      fullPath: "/teams";
      preLoaderRoute: typeof TeamsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/new": {
      id: "/teams/new";
      path: "/teams/new";
      fullPath: "/teams/new";
      preLoaderRoute: typeof TeamsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/join": {
      id: "/teams/join";
      path: "/teams/join";
      fullPath: "/teams/join";
      preLoaderRoute: typeof TeamsJoinRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/team/$program/$number": {
      id: "/team/$program/$number";
      path: "/team/$program/$number";
      fullPath: "/team/$program/$number";
      preLoaderRoute: typeof TeamProgramNumberRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/team/$program/$number/": {
      id: "/team/$program/$number/";
      path: "/";
      fullPath: "/team/$program/$number/";
      preLoaderRoute: typeof TeamProgramNumberIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/settings/": {
      id: "/team/$program/$number/settings/";
      path: "/settings";
      fullPath: "/team/$program/$number/settings";
      preLoaderRoute: typeof TeamProgramNumberSettingsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/robots/": {
      id: "/team/$program/$number/robots/";
      path: "/robots";
      fullPath: "/team/$program/$number/robots";
      preLoaderRoute: typeof TeamProgramNumberRobotsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/": {
      id: "/team/$program/$number/parts/";
      path: "/parts";
      fullPath: "/team/$program/$number/parts";
      preLoaderRoute: typeof TeamProgramNumberPartsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/orders/": {
      id: "/team/$program/$number/orders/";
      path: "/orders";
      fullPath: "/team/$program/$number/orders";
      preLoaderRoute: typeof TeamProgramNumberOrdersIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/members/": {
      id: "/team/$program/$number/members/";
      path: "/members";
      fullPath: "/team/$program/$number/members";
      preLoaderRoute: typeof TeamProgramNumberMembersIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/new/": {
      id: "/team/$program/$number/parts/new/";
      path: "/parts/new";
      fullPath: "/team/$program/$number/parts/new";
      preLoaderRoute: typeof TeamProgramNumberPartsNewIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/$partId/": {
      id: "/team/$program/$number/parts/$partId/";
      path: "/parts/$partId";
      fullPath: "/team/$program/$number/parts/$partId";
      preLoaderRoute: typeof TeamProgramNumberPartsPartIdIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/orders/$orderId/": {
      id: "/team/$program/$number/orders/$orderId/";
      path: "/orders/$orderId";
      fullPath: "/team/$program/$number/orders/$orderId";
      preLoaderRoute: typeof TeamProgramNumberOrdersOrderIdIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/$partId/edit/": {
      id: "/team/$program/$number/parts/$partId/edit/";
      path: "/parts/$partId/edit";
      fullPath: "/team/$program/$number/parts/$partId/edit";
      preLoaderRoute: typeof TeamProgramNumberPartsPartIdEditIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
  }
}

interface TeamProgramNumberRouteChildren {
  TeamProgramNumberIndexRoute: typeof TeamProgramNumberIndexRoute;
  TeamProgramNumberMembersIndexRoute: typeof TeamProgramNumberMembersIndexRoute;
  TeamProgramNumberOrdersIndexRoute: typeof TeamProgramNumberOrdersIndexRoute;
  TeamProgramNumberPartsIndexRoute: typeof TeamProgramNumberPartsIndexRoute;
  TeamProgramNumberRobotsIndexRoute: typeof TeamProgramNumberRobotsIndexRoute;
  TeamProgramNumberSettingsIndexRoute: typeof TeamProgramNumberSettingsIndexRoute;
  TeamProgramNumberOrdersOrderIdIndexRoute: typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  TeamProgramNumberPartsPartIdIndexRoute: typeof TeamProgramNumberPartsPartIdIndexRoute;
  TeamProgramNumberPartsNewIndexRoute: typeof TeamProgramNumberPartsNewIndexRoute;
  TeamProgramNumberPartsPartIdEditIndexRoute: typeof TeamProgramNumberPartsPartIdEditIndexRoute;
}

const TeamProgramNumberRouteChildren: TeamProgramNumberRouteChildren = {
  TeamProgramNumberIndexRoute: TeamProgramNumberIndexRoute,
  TeamProgramNumberMembersIndexRoute: TeamProgramNumberMembersIndexRoute,
  TeamProgramNumberOrdersIndexRoute: TeamProgramNumberOrdersIndexRoute,
  TeamProgramNumberPartsIndexRoute: TeamProgramNumberPartsIndexRoute,
  TeamProgramNumberRobotsIndexRoute: TeamProgramNumberRobotsIndexRoute,
  TeamProgramNumberSettingsIndexRoute: TeamProgramNumberSettingsIndexRoute,
  TeamProgramNumberOrdersOrderIdIndexRoute:
    TeamProgramNumberOrdersOrderIdIndexRoute,
  TeamProgramNumberPartsPartIdIndexRoute:
    TeamProgramNumberPartsPartIdIndexRoute,
  TeamProgramNumberPartsNewIndexRoute: TeamProgramNumberPartsNewIndexRoute,
  TeamProgramNumberPartsPartIdEditIndexRoute:
    TeamProgramNumberPartsPartIdEditIndexRoute,
};

const TeamProgramNumberRouteWithChildren =
  TeamProgramNumberRoute._addFileChildren(TeamProgramNumberRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VendorsRoute: VendorsRoute,
  TeamsJoinRoute: TeamsJoinRoute,
  TeamsNewRoute: TeamsNewRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TeamProgramNumberRoute: TeamProgramNumberRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
