/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsNewRouteImport } from './routes/teams/new'
import { Route as TeamsJoinRouteImport } from './routes/teams/join'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as TeamsTeamIdSettingsIndexRouteImport } from './routes/teams/$teamId/settings/index'
import { Route as TeamsTeamIdRobotsIndexRouteImport } from './routes/teams/$teamId/robots/index'
import { Route as TeamsTeamIdPartsIndexRouteImport } from './routes/teams/$teamId/parts/index'
import { Route as TeamsTeamIdOrdersIndexRouteImport } from './routes/teams/$teamId/orders/index'
import { Route as TeamsTeamIdMembersIndexRouteImport } from './routes/teams/$teamId/members/index'
import { Route as TeamsTeamIdPartsPartIdRouteImport } from './routes/teams/$teamId/parts/$partId'
import { Route as TeamsTeamIdOrdersOrderIdRouteImport } from './routes/teams/$teamId/orders/$orderId'
import { Route as TeamsTeamIdRobotsRobotIdIndexRouteImport } from './routes/teams/$teamId/robots/$robotId/index'
import { Route as TeamsTeamIdRobotsRobotIdBomIndexRouteImport } from './routes/teams/$teamId/robots/$robotId/bom/index'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsJoinRoute = TeamsJoinRouteImport.update({
  id: '/teams/join',
  path: '/teams/join',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdSettingsIndexRoute =
  TeamsTeamIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const TeamsTeamIdRobotsIndexRoute = TeamsTeamIdRobotsIndexRouteImport.update({
  id: '/robots/',
  path: '/robots/',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdPartsIndexRoute = TeamsTeamIdPartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdOrdersIndexRoute = TeamsTeamIdOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdMembersIndexRoute = TeamsTeamIdMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdPartsPartIdRoute = TeamsTeamIdPartsPartIdRouteImport.update({
  id: '/parts/$partId',
  path: '/parts/$partId',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdOrdersOrderIdRoute =
  TeamsTeamIdOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const TeamsTeamIdRobotsRobotIdIndexRoute =
  TeamsTeamIdRobotsRobotIdIndexRouteImport.update({
    id: '/robots/$robotId/',
    path: '/robots/$robotId/',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const TeamsTeamIdRobotsRobotIdBomIndexRoute =
  TeamsTeamIdRobotsRobotIdBomIndexRouteImport.update({
    id: '/robots/$robotId/bom/',
    path: '/robots/$robotId/bom/',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/vendors': typeof VendorsRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/join': typeof TeamsJoinRoute
  '/teams/new': typeof TeamsNewRoute
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/orders/$orderId': typeof TeamsTeamIdOrdersOrderIdRoute
  '/teams/$teamId/parts/$partId': typeof TeamsTeamIdPartsPartIdRoute
  '/teams/$teamId/members': typeof TeamsTeamIdMembersIndexRoute
  '/teams/$teamId/orders': typeof TeamsTeamIdOrdersIndexRoute
  '/teams/$teamId/parts': typeof TeamsTeamIdPartsIndexRoute
  '/teams/$teamId/robots': typeof TeamsTeamIdRobotsIndexRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsIndexRoute
  '/teams/$teamId/robots/$robotId': typeof TeamsTeamIdRobotsRobotIdIndexRoute
  '/teams/$teamId/robots/$robotId/bom': typeof TeamsTeamIdRobotsRobotIdBomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/vendors': typeof VendorsRoute
  '/teams/join': typeof TeamsJoinRoute
  '/teams/new': typeof TeamsNewRoute
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/orders/$orderId': typeof TeamsTeamIdOrdersOrderIdRoute
  '/teams/$teamId/parts/$partId': typeof TeamsTeamIdPartsPartIdRoute
  '/teams/$teamId/members': typeof TeamsTeamIdMembersIndexRoute
  '/teams/$teamId/orders': typeof TeamsTeamIdOrdersIndexRoute
  '/teams/$teamId/parts': typeof TeamsTeamIdPartsIndexRoute
  '/teams/$teamId/robots': typeof TeamsTeamIdRobotsIndexRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsIndexRoute
  '/teams/$teamId/robots/$robotId': typeof TeamsTeamIdRobotsRobotIdIndexRoute
  '/teams/$teamId/robots/$robotId/bom': typeof TeamsTeamIdRobotsRobotIdBomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/vendors': typeof VendorsRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/join': typeof TeamsJoinRoute
  '/teams/new': typeof TeamsNewRoute
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/orders/$orderId': typeof TeamsTeamIdOrdersOrderIdRoute
  '/teams/$teamId/parts/$partId': typeof TeamsTeamIdPartsPartIdRoute
  '/teams/$teamId/members/': typeof TeamsTeamIdMembersIndexRoute
  '/teams/$teamId/orders/': typeof TeamsTeamIdOrdersIndexRoute
  '/teams/$teamId/parts/': typeof TeamsTeamIdPartsIndexRoute
  '/teams/$teamId/robots/': typeof TeamsTeamIdRobotsIndexRoute
  '/teams/$teamId/settings/': typeof TeamsTeamIdSettingsIndexRoute
  '/teams/$teamId/robots/$robotId/': typeof TeamsTeamIdRobotsRobotIdIndexRoute
  '/teams/$teamId/robots/$robotId/bom/': typeof TeamsTeamIdRobotsRobotIdBomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/vendors'
    | '/teams/$teamId'
    | '/teams/join'
    | '/teams/new'
    | '/teams'
    | '/teams/$teamId/'
    | '/teams/$teamId/orders/$orderId'
    | '/teams/$teamId/parts/$partId'
    | '/teams/$teamId/members'
    | '/teams/$teamId/orders'
    | '/teams/$teamId/parts'
    | '/teams/$teamId/robots'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/robots/$robotId'
    | '/teams/$teamId/robots/$robotId/bom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/vendors'
    | '/teams/join'
    | '/teams/new'
    | '/teams'
    | '/teams/$teamId'
    | '/teams/$teamId/orders/$orderId'
    | '/teams/$teamId/parts/$partId'
    | '/teams/$teamId/members'
    | '/teams/$teamId/orders'
    | '/teams/$teamId/parts'
    | '/teams/$teamId/robots'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/robots/$robotId'
    | '/teams/$teamId/robots/$robotId/bom'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/vendors'
    | '/teams/$teamId'
    | '/teams/join'
    | '/teams/new'
    | '/teams/'
    | '/teams/$teamId/'
    | '/teams/$teamId/orders/$orderId'
    | '/teams/$teamId/parts/$partId'
    | '/teams/$teamId/members/'
    | '/teams/$teamId/orders/'
    | '/teams/$teamId/parts/'
    | '/teams/$teamId/robots/'
    | '/teams/$teamId/settings/'
    | '/teams/$teamId/robots/$robotId/'
    | '/teams/$teamId/robots/$robotId/bom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  VendorsRoute: typeof VendorsRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRouteWithChildren
  TeamsJoinRoute: typeof TeamsJoinRoute
  TeamsNewRoute: typeof TeamsNewRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/join': {
      id: '/teams/join'
      path: '/teams/join'
      fullPath: '/teams/join'
      preLoaderRoute: typeof TeamsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/settings/': {
      id: '/teams/$teamId/settings/'
      path: '/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof TeamsTeamIdSettingsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/robots/': {
      id: '/teams/$teamId/robots/'
      path: '/robots'
      fullPath: '/teams/$teamId/robots'
      preLoaderRoute: typeof TeamsTeamIdRobotsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/parts/': {
      id: '/teams/$teamId/parts/'
      path: '/parts'
      fullPath: '/teams/$teamId/parts'
      preLoaderRoute: typeof TeamsTeamIdPartsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/orders/': {
      id: '/teams/$teamId/orders/'
      path: '/orders'
      fullPath: '/teams/$teamId/orders'
      preLoaderRoute: typeof TeamsTeamIdOrdersIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/members/': {
      id: '/teams/$teamId/members/'
      path: '/members'
      fullPath: '/teams/$teamId/members'
      preLoaderRoute: typeof TeamsTeamIdMembersIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/parts/$partId': {
      id: '/teams/$teamId/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/teams/$teamId/parts/$partId'
      preLoaderRoute: typeof TeamsTeamIdPartsPartIdRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/orders/$orderId': {
      id: '/teams/$teamId/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/teams/$teamId/orders/$orderId'
      preLoaderRoute: typeof TeamsTeamIdOrdersOrderIdRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/robots/$robotId/': {
      id: '/teams/$teamId/robots/$robotId/'
      path: '/robots/$robotId'
      fullPath: '/teams/$teamId/robots/$robotId'
      preLoaderRoute: typeof TeamsTeamIdRobotsRobotIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/robots/$robotId/bom/': {
      id: '/teams/$teamId/robots/$robotId/bom/'
      path: '/robots/$robotId/bom'
      fullPath: '/teams/$teamId/robots/$robotId/bom'
      preLoaderRoute: typeof TeamsTeamIdRobotsRobotIdBomIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
  }
}

interface TeamsTeamIdRouteChildren {
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  TeamsTeamIdOrdersOrderIdRoute: typeof TeamsTeamIdOrdersOrderIdRoute
  TeamsTeamIdPartsPartIdRoute: typeof TeamsTeamIdPartsPartIdRoute
  TeamsTeamIdMembersIndexRoute: typeof TeamsTeamIdMembersIndexRoute
  TeamsTeamIdOrdersIndexRoute: typeof TeamsTeamIdOrdersIndexRoute
  TeamsTeamIdPartsIndexRoute: typeof TeamsTeamIdPartsIndexRoute
  TeamsTeamIdRobotsIndexRoute: typeof TeamsTeamIdRobotsIndexRoute
  TeamsTeamIdSettingsIndexRoute: typeof TeamsTeamIdSettingsIndexRoute
  TeamsTeamIdRobotsRobotIdIndexRoute: typeof TeamsTeamIdRobotsRobotIdIndexRoute
  TeamsTeamIdRobotsRobotIdBomIndexRoute: typeof TeamsTeamIdRobotsRobotIdBomIndexRoute
}

const TeamsTeamIdRouteChildren: TeamsTeamIdRouteChildren = {
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  TeamsTeamIdOrdersOrderIdRoute: TeamsTeamIdOrdersOrderIdRoute,
  TeamsTeamIdPartsPartIdRoute: TeamsTeamIdPartsPartIdRoute,
  TeamsTeamIdMembersIndexRoute: TeamsTeamIdMembersIndexRoute,
  TeamsTeamIdOrdersIndexRoute: TeamsTeamIdOrdersIndexRoute,
  TeamsTeamIdPartsIndexRoute: TeamsTeamIdPartsIndexRoute,
  TeamsTeamIdRobotsIndexRoute: TeamsTeamIdRobotsIndexRoute,
  TeamsTeamIdSettingsIndexRoute: TeamsTeamIdSettingsIndexRoute,
  TeamsTeamIdRobotsRobotIdIndexRoute: TeamsTeamIdRobotsRobotIdIndexRoute,
  TeamsTeamIdRobotsRobotIdBomIndexRoute: TeamsTeamIdRobotsRobotIdBomIndexRoute,
}

const TeamsTeamIdRouteWithChildren = TeamsTeamIdRoute._addFileChildren(
  TeamsTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  VendorsRoute: VendorsRoute,
  TeamsTeamIdRoute: TeamsTeamIdRouteWithChildren,
  TeamsJoinRoute: TeamsJoinRoute,
  TeamsNewRoute: TeamsNewRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
