/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VendorsRouteImport } from "./routes/vendors";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TeamsNewRouteImport } from "./routes/teams/new";
import { Route as TeamsTeamIdRouteImport } from "./routes/teams/$teamId";
import { Route as TeamsTeamIdPartsRouteImport } from "./routes/teams/$teamId/parts";
import { Route as TeamsTeamIdOrdersRouteImport } from "./routes/teams/$teamId/orders";
import { Route as TeamsTeamIdMembersRouteImport } from "./routes/teams/$teamId/members";
import { Route as TeamsTeamIdBomRouteImport } from "./routes/teams/$teamId/bom";
import { Route as TeamsTeamIdPartsNewRouteImport } from "./routes/teams/$teamId/parts/new";
import { Route as TeamsTeamIdPartsPartIdRouteImport } from "./routes/teams/$teamId/parts/$partId";
import { Route as TeamsTeamIdOrdersNewRouteImport } from "./routes/teams/$teamId/orders/new";
import { Route as TeamsTeamIdOrdersOrderIdRouteImport } from "./routes/teams/$teamId/orders/$orderId";
import { Route as TeamsTeamIdPartsPartIdEditRouteImport } from "./routes/teams/$teamId/parts/$partId/edit";
import { Route as TeamsTeamIdOrdersOrderIdEditRouteImport } from "./routes/teams/$teamId/orders/$orderId/edit";

const VendorsRoute = VendorsRouteImport.update({
  id: "/vendors",
  path: "/vendors",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: "/teams/new",
  path: "/teams/new",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: "/teams/$teamId",
  path: "/teams/$teamId",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsTeamIdPartsRoute = TeamsTeamIdPartsRouteImport.update({
  id: "/parts",
  path: "/parts",
  getParentRoute: () => TeamsTeamIdRoute,
} as any);
const TeamsTeamIdOrdersRoute = TeamsTeamIdOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => TeamsTeamIdRoute,
} as any);
const TeamsTeamIdMembersRoute = TeamsTeamIdMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => TeamsTeamIdRoute,
} as any);
const TeamsTeamIdBomRoute = TeamsTeamIdBomRouteImport.update({
  id: "/bom",
  path: "/bom",
  getParentRoute: () => TeamsTeamIdRoute,
} as any);
const TeamsTeamIdPartsNewRoute = TeamsTeamIdPartsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => TeamsTeamIdPartsRoute,
} as any);
const TeamsTeamIdPartsPartIdRoute = TeamsTeamIdPartsPartIdRouteImport.update({
  id: "/$partId",
  path: "/$partId",
  getParentRoute: () => TeamsTeamIdPartsRoute,
} as any);
const TeamsTeamIdOrdersNewRoute = TeamsTeamIdOrdersNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => TeamsTeamIdOrdersRoute,
} as any);
const TeamsTeamIdOrdersOrderIdRoute =
  TeamsTeamIdOrdersOrderIdRouteImport.update({
    id: "/$orderId",
    path: "/$orderId",
    getParentRoute: () => TeamsTeamIdOrdersRoute,
  } as any);
const TeamsTeamIdPartsPartIdEditRoute =
  TeamsTeamIdPartsPartIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => TeamsTeamIdPartsPartIdRoute,
  } as any);
const TeamsTeamIdOrdersOrderIdEditRoute =
  TeamsTeamIdOrdersOrderIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => TeamsTeamIdOrdersOrderIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/$teamId": typeof TeamsTeamIdRouteWithChildren;
  "/teams/new": typeof TeamsNewRoute;
  "/teams/$teamId/bom": typeof TeamsTeamIdBomRoute;
  "/teams/$teamId/members": typeof TeamsTeamIdMembersRoute;
  "/teams/$teamId/orders": typeof TeamsTeamIdOrdersRouteWithChildren;
  "/teams/$teamId/parts": typeof TeamsTeamIdPartsRouteWithChildren;
  "/teams/$teamId/orders/$orderId": typeof TeamsTeamIdOrdersOrderIdRouteWithChildren;
  "/teams/$teamId/orders/new": typeof TeamsTeamIdOrdersNewRoute;
  "/teams/$teamId/parts/$partId": typeof TeamsTeamIdPartsPartIdRouteWithChildren;
  "/teams/$teamId/parts/new": typeof TeamsTeamIdPartsNewRoute;
  "/teams/$teamId/orders/$orderId/edit": typeof TeamsTeamIdOrdersOrderIdEditRoute;
  "/teams/$teamId/parts/$partId/edit": typeof TeamsTeamIdPartsPartIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/$teamId": typeof TeamsTeamIdRouteWithChildren;
  "/teams/new": typeof TeamsNewRoute;
  "/teams/$teamId/bom": typeof TeamsTeamIdBomRoute;
  "/teams/$teamId/members": typeof TeamsTeamIdMembersRoute;
  "/teams/$teamId/orders": typeof TeamsTeamIdOrdersRouteWithChildren;
  "/teams/$teamId/parts": typeof TeamsTeamIdPartsRouteWithChildren;
  "/teams/$teamId/orders/$orderId": typeof TeamsTeamIdOrdersOrderIdRouteWithChildren;
  "/teams/$teamId/orders/new": typeof TeamsTeamIdOrdersNewRoute;
  "/teams/$teamId/parts/$partId": typeof TeamsTeamIdPartsPartIdRouteWithChildren;
  "/teams/$teamId/parts/new": typeof TeamsTeamIdPartsNewRoute;
  "/teams/$teamId/orders/$orderId/edit": typeof TeamsTeamIdOrdersOrderIdEditRoute;
  "/teams/$teamId/parts/$partId/edit": typeof TeamsTeamIdPartsPartIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/$teamId": typeof TeamsTeamIdRouteWithChildren;
  "/teams/new": typeof TeamsNewRoute;
  "/teams/$teamId/bom": typeof TeamsTeamIdBomRoute;
  "/teams/$teamId/members": typeof TeamsTeamIdMembersRoute;
  "/teams/$teamId/orders": typeof TeamsTeamIdOrdersRouteWithChildren;
  "/teams/$teamId/parts": typeof TeamsTeamIdPartsRouteWithChildren;
  "/teams/$teamId/orders/$orderId": typeof TeamsTeamIdOrdersOrderIdRouteWithChildren;
  "/teams/$teamId/orders/new": typeof TeamsTeamIdOrdersNewRoute;
  "/teams/$teamId/parts/$partId": typeof TeamsTeamIdPartsPartIdRouteWithChildren;
  "/teams/$teamId/parts/new": typeof TeamsTeamIdPartsNewRoute;
  "/teams/$teamId/orders/$orderId/edit": typeof TeamsTeamIdOrdersOrderIdEditRoute;
  "/teams/$teamId/parts/$partId/edit": typeof TeamsTeamIdPartsPartIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/vendors"
    | "/teams/$teamId"
    | "/teams/new"
    | "/teams/$teamId/bom"
    | "/teams/$teamId/members"
    | "/teams/$teamId/orders"
    | "/teams/$teamId/parts"
    | "/teams/$teamId/orders/$orderId"
    | "/teams/$teamId/orders/new"
    | "/teams/$teamId/parts/$partId"
    | "/teams/$teamId/parts/new"
    | "/teams/$teamId/orders/$orderId/edit"
    | "/teams/$teamId/parts/$partId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/vendors"
    | "/teams/$teamId"
    | "/teams/new"
    | "/teams/$teamId/bom"
    | "/teams/$teamId/members"
    | "/teams/$teamId/orders"
    | "/teams/$teamId/parts"
    | "/teams/$teamId/orders/$orderId"
    | "/teams/$teamId/orders/new"
    | "/teams/$teamId/parts/$partId"
    | "/teams/$teamId/parts/new"
    | "/teams/$teamId/orders/$orderId/edit"
    | "/teams/$teamId/parts/$partId/edit";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/vendors"
    | "/teams/$teamId"
    | "/teams/new"
    | "/teams/$teamId/bom"
    | "/teams/$teamId/members"
    | "/teams/$teamId/orders"
    | "/teams/$teamId/parts"
    | "/teams/$teamId/orders/$orderId"
    | "/teams/$teamId/orders/new"
    | "/teams/$teamId/parts/$partId"
    | "/teams/$teamId/parts/new"
    | "/teams/$teamId/orders/$orderId/edit"
    | "/teams/$teamId/parts/$partId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  VendorsRoute: typeof VendorsRoute;
  TeamsTeamIdRoute: typeof TeamsTeamIdRouteWithChildren;
  TeamsNewRoute: typeof TeamsNewRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vendors": {
      id: "/vendors";
      path: "/vendors";
      fullPath: "/vendors";
      preLoaderRoute: typeof VendorsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/new": {
      id: "/teams/new";
      path: "/teams/new";
      fullPath: "/teams/new";
      preLoaderRoute: typeof TeamsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/$teamId": {
      id: "/teams/$teamId";
      path: "/teams/$teamId";
      fullPath: "/teams/$teamId";
      preLoaderRoute: typeof TeamsTeamIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/$teamId/parts": {
      id: "/teams/$teamId/parts";
      path: "/parts";
      fullPath: "/teams/$teamId/parts";
      preLoaderRoute: typeof TeamsTeamIdPartsRouteImport;
      parentRoute: typeof TeamsTeamIdRoute;
    };
    "/teams/$teamId/orders": {
      id: "/teams/$teamId/orders";
      path: "/orders";
      fullPath: "/teams/$teamId/orders";
      preLoaderRoute: typeof TeamsTeamIdOrdersRouteImport;
      parentRoute: typeof TeamsTeamIdRoute;
    };
    "/teams/$teamId/members": {
      id: "/teams/$teamId/members";
      path: "/members";
      fullPath: "/teams/$teamId/members";
      preLoaderRoute: typeof TeamsTeamIdMembersRouteImport;
      parentRoute: typeof TeamsTeamIdRoute;
    };
    "/teams/$teamId/bom": {
      id: "/teams/$teamId/bom";
      path: "/bom";
      fullPath: "/teams/$teamId/bom";
      preLoaderRoute: typeof TeamsTeamIdBomRouteImport;
      parentRoute: typeof TeamsTeamIdRoute;
    };
    "/teams/$teamId/parts/new": {
      id: "/teams/$teamId/parts/new";
      path: "/new";
      fullPath: "/teams/$teamId/parts/new";
      preLoaderRoute: typeof TeamsTeamIdPartsNewRouteImport;
      parentRoute: typeof TeamsTeamIdPartsRoute;
    };
    "/teams/$teamId/parts/$partId": {
      id: "/teams/$teamId/parts/$partId";
      path: "/$partId";
      fullPath: "/teams/$teamId/parts/$partId";
      preLoaderRoute: typeof TeamsTeamIdPartsPartIdRouteImport;
      parentRoute: typeof TeamsTeamIdPartsRoute;
    };
    "/teams/$teamId/orders/new": {
      id: "/teams/$teamId/orders/new";
      path: "/new";
      fullPath: "/teams/$teamId/orders/new";
      preLoaderRoute: typeof TeamsTeamIdOrdersNewRouteImport;
      parentRoute: typeof TeamsTeamIdOrdersRoute;
    };
    "/teams/$teamId/orders/$orderId": {
      id: "/teams/$teamId/orders/$orderId";
      path: "/$orderId";
      fullPath: "/teams/$teamId/orders/$orderId";
      preLoaderRoute: typeof TeamsTeamIdOrdersOrderIdRouteImport;
      parentRoute: typeof TeamsTeamIdOrdersRoute;
    };
    "/teams/$teamId/parts/$partId/edit": {
      id: "/teams/$teamId/parts/$partId/edit";
      path: "/edit";
      fullPath: "/teams/$teamId/parts/$partId/edit";
      preLoaderRoute: typeof TeamsTeamIdPartsPartIdEditRouteImport;
      parentRoute: typeof TeamsTeamIdPartsPartIdRoute;
    };
    "/teams/$teamId/orders/$orderId/edit": {
      id: "/teams/$teamId/orders/$orderId/edit";
      path: "/edit";
      fullPath: "/teams/$teamId/orders/$orderId/edit";
      preLoaderRoute: typeof TeamsTeamIdOrdersOrderIdEditRouteImport;
      parentRoute: typeof TeamsTeamIdOrdersOrderIdRoute;
    };
  }
}

interface TeamsTeamIdOrdersOrderIdRouteChildren {
  TeamsTeamIdOrdersOrderIdEditRoute: typeof TeamsTeamIdOrdersOrderIdEditRoute;
}

const TeamsTeamIdOrdersOrderIdRouteChildren: TeamsTeamIdOrdersOrderIdRouteChildren =
  {
    TeamsTeamIdOrdersOrderIdEditRoute: TeamsTeamIdOrdersOrderIdEditRoute,
  };

const TeamsTeamIdOrdersOrderIdRouteWithChildren =
  TeamsTeamIdOrdersOrderIdRoute._addFileChildren(
    TeamsTeamIdOrdersOrderIdRouteChildren
  );

interface TeamsTeamIdOrdersRouteChildren {
  TeamsTeamIdOrdersOrderIdRoute: typeof TeamsTeamIdOrdersOrderIdRouteWithChildren;
  TeamsTeamIdOrdersNewRoute: typeof TeamsTeamIdOrdersNewRoute;
}

const TeamsTeamIdOrdersRouteChildren: TeamsTeamIdOrdersRouteChildren = {
  TeamsTeamIdOrdersOrderIdRoute: TeamsTeamIdOrdersOrderIdRouteWithChildren,
  TeamsTeamIdOrdersNewRoute: TeamsTeamIdOrdersNewRoute,
};

const TeamsTeamIdOrdersRouteWithChildren =
  TeamsTeamIdOrdersRoute._addFileChildren(TeamsTeamIdOrdersRouteChildren);

interface TeamsTeamIdPartsPartIdRouteChildren {
  TeamsTeamIdPartsPartIdEditRoute: typeof TeamsTeamIdPartsPartIdEditRoute;
}

const TeamsTeamIdPartsPartIdRouteChildren: TeamsTeamIdPartsPartIdRouteChildren =
  {
    TeamsTeamIdPartsPartIdEditRoute: TeamsTeamIdPartsPartIdEditRoute,
  };

const TeamsTeamIdPartsPartIdRouteWithChildren =
  TeamsTeamIdPartsPartIdRoute._addFileChildren(
    TeamsTeamIdPartsPartIdRouteChildren
  );

interface TeamsTeamIdPartsRouteChildren {
  TeamsTeamIdPartsPartIdRoute: typeof TeamsTeamIdPartsPartIdRouteWithChildren;
  TeamsTeamIdPartsNewRoute: typeof TeamsTeamIdPartsNewRoute;
}

const TeamsTeamIdPartsRouteChildren: TeamsTeamIdPartsRouteChildren = {
  TeamsTeamIdPartsPartIdRoute: TeamsTeamIdPartsPartIdRouteWithChildren,
  TeamsTeamIdPartsNewRoute: TeamsTeamIdPartsNewRoute,
};

const TeamsTeamIdPartsRouteWithChildren =
  TeamsTeamIdPartsRoute._addFileChildren(TeamsTeamIdPartsRouteChildren);

interface TeamsTeamIdRouteChildren {
  TeamsTeamIdBomRoute: typeof TeamsTeamIdBomRoute;
  TeamsTeamIdMembersRoute: typeof TeamsTeamIdMembersRoute;
  TeamsTeamIdOrdersRoute: typeof TeamsTeamIdOrdersRouteWithChildren;
  TeamsTeamIdPartsRoute: typeof TeamsTeamIdPartsRouteWithChildren;
}

const TeamsTeamIdRouteChildren: TeamsTeamIdRouteChildren = {
  TeamsTeamIdBomRoute: TeamsTeamIdBomRoute,
  TeamsTeamIdMembersRoute: TeamsTeamIdMembersRoute,
  TeamsTeamIdOrdersRoute: TeamsTeamIdOrdersRouteWithChildren,
  TeamsTeamIdPartsRoute: TeamsTeamIdPartsRouteWithChildren,
};

const TeamsTeamIdRouteWithChildren = TeamsTeamIdRoute._addFileChildren(
  TeamsTeamIdRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  VendorsRoute: VendorsRoute,
  TeamsTeamIdRoute: TeamsTeamIdRouteWithChildren,
  TeamsNewRoute: TeamsNewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
